name: Node CI
on:
  push:
    tags:
      - v1.*.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set env
      run: |
        echo ::set-env name=LATEST_DIR::vp/latest
        echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
        echo ::set-env name=VERSIONED_DIR::vp/${GITHUB_REF:10}
      env:
        CI: true
    - name: ECHO dirs
      run: echo "latest ${LATEST_DIR} - versioned ${VERSIONED_DIR}"
