name: Node CI
on:
  push:
    tags:
      - 1.*.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set env
      run: |
        echo "LATEST_DIR=vp/latest" >> $GITHUB_ENV
        echo "VERSIONED_DIR=vp/{GITHUB_REF:10}" >> $GITHUB_ENV
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: yarn install and build
      run: |
        yarn install --pure-lockfile
        yarn build
      env:
        CI: true
    - name: ECHO upload directories
      run: echo "latest ${LATEST_DIR} | versioned ${VERSIONED_DIR}"
    - name: Copy to S3 | latest
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'dist'
        DEST_DIR: ${LATEST_DIR}
    - name: Copy to S3 | versioned
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'dist'
        DEST_DIR: ${VERSIONED_DIR}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Invalidate CloudFront cache
      run: aws cloudfront create-invalidation --distribution-id ${AWS_DISTRIBUTION_ID} --paths "/vp/latest/*"
      env:
          AWS_DISTRIBUTION_ID: ${{secrets.AWS_DISTRIBUTION_ID}}
