name: Node CI
on:
  push:
    tags:
      - v1.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set env
      run: |
        echo ::set-env name=LATEST_DIR::vp/latest
        echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
        echo ::set-env name=VERSIONED_DIR::vp/$(echo ${RELEASE_VERSION})
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: yarn install and build
      run: |
        yarn install --pure-lockfile
        yarn build
      env:
        CI: true
    - name: ECHO dirs
      run: echo "latest $(LATEST_DIR) - versioned $(VERSIONED_DIR)"
